name: "✨ 功能建议"
description: "建议新功能或改进现有功能"
title: "【功能建议】"
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！请详细描述您希望的功能，这将帮助我们更好地理解您的需求。

  - type: textarea
    id: feature-description
    attributes:
      label: "功能描述"
      description: "请详细描述您希望的功能"
      placeholder: "我希望能够..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "使用场景"
      description: "请描述这个功能的使用场景和解决的问题"
      placeholder: |
        - 当我想要...的时候
        - 这个功能可以帮助...
        - 解决了...的问题
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: "功能类型"
      description: "这个功能属于哪个类别？"
      options:
        - "新增API接口"
        - "改进现有接口"
        - "数据源扩展"
        - "性能优化"
        - "用户体验改进"
        - "其他"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "优先级（可选）"
      description: "您认为这个功能的优先级是？"
      options:
        - "高 - 急需此功能"
        - "中 - 希望有此功能"
        - "低 - 可有可无"
    validations:
      required: false

  - type: textarea
    id: interface-spec
    attributes:
      label: "接口规格（可选）"
      description: "如果是API相关的功能，请描述期望的接口格式"
      placeholder: |
        请求：GET /your-api
        参数：
        - param1: 描述
        - param2: 描述
        
        响应：
        {
          "data": "期望的数据格式",
          "message": "响应信息"
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: "使用示例（可选）"
      description: "请提供一些使用示例或参考"
      placeholder: |
        例如：
        1. 类似于某某网站的功能
        2. 参考某某API的实现
        3. 具体的使用示例
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "替代方案（可选）"
      description: "您是否考虑过其他解决方案？"
      placeholder: "目前我通过...方式解决，但是..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "其他信息（可选）"
      description: "任何其他有助于实现这个功能的信息"
    validations:
      required: false
